// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxfECJ7-auu4qhHmJOUuGOKoclGaYvTbQ',
    appId: '1:491979538279:web:a72413ac8a0c77bc6f79c2',
    messagingSenderId: '491979538279',
    projectId: 'ks-charity-app',
    authDomain: 'ks-charity-app.firebaseapp.com',
    storageBucket: 'ks-charity-app.firebasestorage.app',
    measurementId: 'G-6CRTPH1N26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgt0hPMEWkcqTNBONJRyOrP1Q-QL7VfKY',
    appId: '1:491979538279:android:703eeb6fa2ae3bc96f79c2',
    messagingSenderId: '491979538279',
    projectId: 'ks-charity-app',
    storageBucket: 'ks-charity-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiO7JbSu2hDSEM8Q15Eh0UkKWX3u7BWCc',
    appId: '1:491979538279:ios:ee42d3c34647e7c46f79c2',
    messagingSenderId: '491979538279',
    projectId: 'ks-charity-app',
    storageBucket: 'ks-charity-app.firebasestorage.app',
    iosBundleId: 'com.example.charityDonationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxfECJ7-auu4qhHmJOUuGOKoclGaYvTbQ',
    appId: '1:491979538279:web:2dc6659097c49d396f79c2',
    messagingSenderId: '491979538279',
    projectId: 'ks-charity-app',
    authDomain: 'ks-charity-app.firebaseapp.com',
    storageBucket: 'ks-charity-app.firebasestorage.app',
    measurementId: 'G-4VW09WRRFG',
  );
}
